//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GUIPagos_PSA.API_Pagos {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="API_GestionPagosSoap", Namespace="http://tempuri.org/")]
    public partial class API_GestionPagos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarPorEstadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback leerPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback leerPorCedulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback leerPorServicioOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public API_GestionPagos() {
            this.Url = global::GUIPagos_PSA.Properties.Settings.Default.GUIPagos_PSA_API_Pagos_API_GestionPagos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListarCompletedEventHandler ListarCompleted;
        
        /// <remarks/>
        public event ListarPorEstadoCompletedEventHandler ListarPorEstadoCompleted;
        
        /// <remarks/>
        public event leerPorIdCompletedEventHandler leerPorIdCompleted;
        
        /// <remarks/>
        public event leerPorCedulaCompletedEventHandler leerPorCedulaCompleted;
        
        /// <remarks/>
        public event leerPorServicioCompletedEventHandler leerPorServicioCompleted;
        
        /// <remarks/>
        public event InsertarCompletedEventHandler InsertarCompleted;
        
        /// <remarks/>
        public event ActualizarCompletedEventHandler ActualizarCompleted;
        
        /// <remarks/>
        public event EliminarCompletedEventHandler EliminarCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Listar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pagos[] Listar() {
            object[] results = this.Invoke("Listar", new object[0]);
            return ((Pagos[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAsync() {
            this.ListarAsync(null);
        }
        
        /// <remarks/>
        public void ListarAsync(object userState) {
            if ((this.ListarOperationCompleted == null)) {
                this.ListarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarOperationCompleted);
            }
            this.InvokeAsync("Listar", new object[0], this.ListarOperationCompleted, userState);
        }
        
        private void OnListarOperationCompleted(object arg) {
            if ((this.ListarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCompleted(this, new ListarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarPorEstado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pagos[] ListarPorEstado(bool estado) {
            object[] results = this.Invoke("ListarPorEstado", new object[] {
                        estado});
            return ((Pagos[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarPorEstadoAsync(bool estado) {
            this.ListarPorEstadoAsync(estado, null);
        }
        
        /// <remarks/>
        public void ListarPorEstadoAsync(bool estado, object userState) {
            if ((this.ListarPorEstadoOperationCompleted == null)) {
                this.ListarPorEstadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarPorEstadoOperationCompleted);
            }
            this.InvokeAsync("ListarPorEstado", new object[] {
                        estado}, this.ListarPorEstadoOperationCompleted, userState);
        }
        
        private void OnListarPorEstadoOperationCompleted(object arg) {
            if ((this.ListarPorEstadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarPorEstadoCompleted(this, new ListarPorEstadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/leerPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pagos leerPorId(int id) {
            object[] results = this.Invoke("leerPorId", new object[] {
                        id});
            return ((Pagos)(results[0]));
        }
        
        /// <remarks/>
        public void leerPorIdAsync(int id) {
            this.leerPorIdAsync(id, null);
        }
        
        /// <remarks/>
        public void leerPorIdAsync(int id, object userState) {
            if ((this.leerPorIdOperationCompleted == null)) {
                this.leerPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnleerPorIdOperationCompleted);
            }
            this.InvokeAsync("leerPorId", new object[] {
                        id}, this.leerPorIdOperationCompleted, userState);
        }
        
        private void OnleerPorIdOperationCompleted(object arg) {
            if ((this.leerPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.leerPorIdCompleted(this, new leerPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/leerPorCedula", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pagos leerPorCedula(string cedula) {
            object[] results = this.Invoke("leerPorCedula", new object[] {
                        cedula});
            return ((Pagos)(results[0]));
        }
        
        /// <remarks/>
        public void leerPorCedulaAsync(string cedula) {
            this.leerPorCedulaAsync(cedula, null);
        }
        
        /// <remarks/>
        public void leerPorCedulaAsync(string cedula, object userState) {
            if ((this.leerPorCedulaOperationCompleted == null)) {
                this.leerPorCedulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnleerPorCedulaOperationCompleted);
            }
            this.InvokeAsync("leerPorCedula", new object[] {
                        cedula}, this.leerPorCedulaOperationCompleted, userState);
        }
        
        private void OnleerPorCedulaOperationCompleted(object arg) {
            if ((this.leerPorCedulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.leerPorCedulaCompleted(this, new leerPorCedulaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/leerPorServicio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pagos leerPorServicio(int id) {
            object[] results = this.Invoke("leerPorServicio", new object[] {
                        id});
            return ((Pagos)(results[0]));
        }
        
        /// <remarks/>
        public void leerPorServicioAsync(int id) {
            this.leerPorServicioAsync(id, null);
        }
        
        /// <remarks/>
        public void leerPorServicioAsync(int id, object userState) {
            if ((this.leerPorServicioOperationCompleted == null)) {
                this.leerPorServicioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnleerPorServicioOperationCompleted);
            }
            this.InvokeAsync("leerPorServicio", new object[] {
                        id}, this.leerPorServicioOperationCompleted, userState);
        }
        
        private void OnleerPorServicioOperationCompleted(object arg) {
            if ((this.leerPorServicioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.leerPorServicioCompleted(this, new leerPorServicioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insertar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Insertar(Pagos pagos) {
            this.Invoke("Insertar", new object[] {
                        pagos});
        }
        
        /// <remarks/>
        public void InsertarAsync(Pagos pagos) {
            this.InsertarAsync(pagos, null);
        }
        
        /// <remarks/>
        public void InsertarAsync(Pagos pagos, object userState) {
            if ((this.InsertarOperationCompleted == null)) {
                this.InsertarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarOperationCompleted);
            }
            this.InvokeAsync("Insertar", new object[] {
                        pagos}, this.InsertarOperationCompleted, userState);
        }
        
        private void OnInsertarOperationCompleted(object arg) {
            if ((this.InsertarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Actualizar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Actualizar(Pagos pagos) {
            this.Invoke("Actualizar", new object[] {
                        pagos});
        }
        
        /// <remarks/>
        public void ActualizarAsync(Pagos pagos) {
            this.ActualizarAsync(pagos, null);
        }
        
        /// <remarks/>
        public void ActualizarAsync(Pagos pagos, object userState) {
            if ((this.ActualizarOperationCompleted == null)) {
                this.ActualizarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarOperationCompleted);
            }
            this.InvokeAsync("Actualizar", new object[] {
                        pagos}, this.ActualizarOperationCompleted, userState);
        }
        
        private void OnActualizarOperationCompleted(object arg) {
            if ((this.ActualizarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Eliminar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Eliminar(int id) {
            this.Invoke("Eliminar", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void EliminarAsync(int id) {
            this.EliminarAsync(id, null);
        }
        
        /// <remarks/>
        public void EliminarAsync(int id, object userState) {
            if ((this.EliminarOperationCompleted == null)) {
                this.EliminarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarOperationCompleted);
            }
            this.InvokeAsync("Eliminar", new object[] {
                        id}, this.EliminarOperationCompleted, userState);
        }
        
        private void OnEliminarOperationCompleted(object arg) {
            if ((this.EliminarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pagos {
        
        private int pagosIDField;
        
        private string cedulaIdentidadField;
        
        private System.Nullable<int> serviciosIDField;
        
        private System.Nullable<System.DateTime> fechaEmisionField;
        
        private System.Nullable<System.DateTime> fechaVencimientoField;
        
        private System.Nullable<decimal> montoTotalField;
        
        private string estadoField;
        
        private System.Nullable<bool> pagosActivosField;
        
        private string cod_pagoField;
        
        private Servicios serviciosField;
        
        private Usuarios usuariosField;
        
        /// <remarks/>
        public int PagosID {
            get {
                return this.pagosIDField;
            }
            set {
                this.pagosIDField = value;
            }
        }
        
        /// <remarks/>
        public string CedulaIdentidad {
            get {
                return this.cedulaIdentidadField;
            }
            set {
                this.cedulaIdentidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ServiciosID {
            get {
                return this.serviciosIDField;
            }
            set {
                this.serviciosIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MontoTotal {
            get {
                return this.montoTotalField;
            }
            set {
                this.montoTotalField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> PagosActivos {
            get {
                return this.pagosActivosField;
            }
            set {
                this.pagosActivosField = value;
            }
        }
        
        /// <remarks/>
        public string cod_pago {
            get {
                return this.cod_pagoField;
            }
            set {
                this.cod_pagoField = value;
            }
        }
        
        /// <remarks/>
        public Servicios Servicios {
            get {
                return this.serviciosField;
            }
            set {
                this.serviciosField = value;
            }
        }
        
        /// <remarks/>
        public Usuarios Usuarios {
            get {
                return this.usuariosField;
            }
            set {
                this.usuariosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Servicios {
        
        private int serviciosIDField;
        
        private string descripcionField;
        
        private System.Nullable<decimal> montoServicioField;
        
        private System.Nullable<bool> servicioActivoField;
        
        private Pagos[] pagosField;
        
        /// <remarks/>
        public int ServiciosID {
            get {
                return this.serviciosIDField;
            }
            set {
                this.serviciosIDField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MontoServicio {
            get {
                return this.montoServicioField;
            }
            set {
                this.montoServicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> ServicioActivo {
            get {
                return this.servicioActivoField;
            }
            set {
                this.servicioActivoField = value;
            }
        }
        
        /// <remarks/>
        public Pagos[] Pagos {
            get {
                return this.pagosField;
            }
            set {
                this.pagosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Notificacion {
        
        private int notificacionIDField;
        
        private string cedulaIdentidadField;
        
        private string descripcionField;
        
        private System.Nullable<System.DateTime> fechaRegistroField;
        
        private string estadoNotificacionField;
        
        private string comentariosResolucionField;
        
        private System.Nullable<bool> notificacionActivaField;
        
        private Usuarios usuariosField;
        
        /// <remarks/>
        public int NotificacionID {
            get {
                return this.notificacionIDField;
            }
            set {
                this.notificacionIDField = value;
            }
        }
        
        /// <remarks/>
        public string CedulaIdentidad {
            get {
                return this.cedulaIdentidadField;
            }
            set {
                this.cedulaIdentidadField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
            }
        }
        
        /// <remarks/>
        public string EstadoNotificacion {
            get {
                return this.estadoNotificacionField;
            }
            set {
                this.estadoNotificacionField = value;
            }
        }
        
        /// <remarks/>
        public string ComentariosResolucion {
            get {
                return this.comentariosResolucionField;
            }
            set {
                this.comentariosResolucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> NotificacionActiva {
            get {
                return this.notificacionActivaField;
            }
            set {
                this.notificacionActivaField = value;
            }
        }
        
        /// <remarks/>
        public Usuarios Usuarios {
            get {
                return this.usuariosField;
            }
            set {
                this.usuariosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuarios {
        
        private string cedulaIdentidadField;
        
        private string nombreField;
        
        private string direccionField;
        
        private string emailField;
        
        private string telefonoField;
        
        private System.Nullable<bool> usuarioActivoField;
        
        private Notificacion[] notificacionField;
        
        private Pagos[] pagosField;
        
        /// <remarks/>
        public string CedulaIdentidad {
            get {
                return this.cedulaIdentidadField;
            }
            set {
                this.cedulaIdentidadField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> UsuarioActivo {
            get {
                return this.usuarioActivoField;
            }
            set {
                this.usuarioActivoField = value;
            }
        }
        
        /// <remarks/>
        public Notificacion[] Notificacion {
            get {
                return this.notificacionField;
            }
            set {
                this.notificacionField = value;
            }
        }
        
        /// <remarks/>
        public Pagos[] Pagos {
            get {
                return this.pagosField;
            }
            set {
                this.pagosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ListarCompletedEventHandler(object sender, ListarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pagos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pagos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ListarPorEstadoCompletedEventHandler(object sender, ListarPorEstadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarPorEstadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarPorEstadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pagos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pagos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void leerPorIdCompletedEventHandler(object sender, leerPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class leerPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal leerPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pagos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pagos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void leerPorCedulaCompletedEventHandler(object sender, leerPorCedulaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class leerPorCedulaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal leerPorCedulaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pagos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pagos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void leerPorServicioCompletedEventHandler(object sender, leerPorServicioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class leerPorServicioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal leerPorServicioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pagos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pagos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void InsertarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ActualizarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void EliminarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591